export {
  DIALOG_SURFACE_HOST_ATTR,
  SURFACE_PORTAL_HOST_ATTR,
  SURFACE_PORTAL_LAYER_ATTR,
  DIALOG_SURFACE_BOUNDARY_ATTR,
  ensureSurfacePortalInteractionTracking,
  resolveSurfacePortalHost,
  isSurfacePortalMode,
  resolveSurfacePortalMount,
  resolveSurfacePortalBoundaryRect,
  resolveSurfacePortalMountRect,
  projectSurfacePortalPosition,
  projectSurfacePortalRect,
  __resetSurfacePortalScopeForTests,
  type SurfacePortalInteractionSnapshot,
  type SurfacePortalHostResolutionOptions,
  type SurfacePortalMode,
  type ResolvedSurfacePortalHost,
  type SurfacePortalBoundaryRect,
  type SurfacePortalRect,
} from './dialogSurfaceScope';
